In [ ]:
import numpy as np
import random
import math

In [ ]:
X1=[1,1,1,1,1,1]
X2=[-1,-1,-1,-1,-1,-1]
X3=[1,-1,-1,1,1,1]
X4=[1,1,-1,-1,-1,-1]

X=np.array([X1,X2,X3,X4])

Y1=[1,1,1]
Y2=[-1,-1,-1]
Y3=[-1,1,1]
Y4=[1,-1,1]

Y=np.array([Y1,Y2,Y3,Y4])

print("X=",X)
print("\nY=",Y)
print("\n\n Dimensions of X : ",X.shape)
print("\n Dimensions of Y : ",Y.shape)

X= [[ 1  1  1  1  1  1]
 [-1 -1 -1 -1 -1 -1]
 [ 1 -1 -1  1  1  1]
 [ 1  1 -1 -1 -1 -1]]

Y= [[ 1  1  1]
 [-1 -1 -1]
 [-1  1  1]
 [ 1 -1  1]]


 Dimensions of X :  (4, 6)

 Dimensions of Y :  (4, 3)


In [ ]:
def calWeight(X,Y):
  return np.dot(X.T,Y)

weight=calWeight(X,Y)
print('W=',weight,end="")

print("\n\n Dimensions of weight matrix:",weight.shape)

W= [[2 2 4]
 [4 0 2]
 [2 2 0]
 [0 4 2]
 [0 4 2]
 [0 4 2]]

 Dimensions of weight matrix: (6, 3)


In [ ]:
def forwardbipolaractivation(matrix,weight):
  matrix[matrix > 0] = 1
  matrix[matrix <= 0] = -1
  return np.array(matrix)

def backwardbipolaractivation(matrix,weight):
  matrix[matrix >= 0] = 1
  matrix[matrix < 0] = -1  
  return np.array(matrix)

In [ ]:
def forward(Y,weight):
  x=np.dot(Y,weight.T)
  return forwardbipolaractivation(x,weight)

In [ ]:
print("\n weight*Y1 = ",forward(Y1,weight)," = X1")
print("\n weight*Y1 = ",forward(Y2,weight)," = X2")
print("\n weight*Y1 = ",forward(Y3,weight)," = X3")
print("\n weight*Y1 = ",forward(Y4,weight)," = X4")

print("\n\n it is observed that the obtained result maths with the original X matrices.\n\n forward testing is 100% accurate. ")


 weight*Y1 =  [1 1 1 1 1 1]  = X1

 weight*Y1 =  [-1 -1 -1 -1 -1 -1]  = X2

 weight*Y1 =  [ 1 -1 -1  1  1  1]  = X3

 weight*Y1 =  [ 1  1 -1 -1 -1 -1]  = X4


 it is observed that the obtained result maths with the original X matrices.

 forward testing is 100% accurate. 


In [ ]:
def backward(X,weight):
  Y=np.dot(weight.T,X)
  return backwardbipolaractivation(Y,weight)
  

In [ ]:
print("\n weight*X1 = ",backward(X1,weight)," = Y1")
print("\n weight*X1 = ",backward(X2,weight)," = Y2")
print("\n weight*X1 = ",backward(X3,weight)," = Y3")
print("\n weight*X1 = ",backward(X4,weight)," = Y4")

print("\n\n it is observed that the obtained result maths with the original X matrices.\n\n forward testing is 100% accurate. ")


 weight*X1 =  [1 1 1]  = Y1

 weight*X1 =  [-1 -1 -1]  = Y2

 weight*X1 =  [-1  1  1]  = Y3

 weight*X1 =  [ 1 -1  1]  = Y4


 it is observed that the obtained result maths with the original X matrices.

 forward testing is 100% accurate. 
